### ISSUE TITLE
ERROR: Error loading VS DTE. Is the correct version of Visual Studio and TwinCAT installed? Is the TcUnit-Runner running with administrator privileges?

### ISSUE THREAD

**Issue by Rickymes** [tcunit/TcUnit-Runner#31] opened 2021-12-15 11:03 UTC
Hi,
I have the same issue described by another user and I have also read your blog about it (https://alltwincat.com/2018/10/04/ci-cd-with-twincat-part-four/), but the problem still remain. Instead of Git as a version control system, I used SubVersion if it can help you to understand the problem. Using the Shell it works fine, reporting the results in a XML file. Probably the versions of Visual Studio and TwinCAT installed are not ok?

![image](https://user-images.githubusercontent.com/96171639/146175055-49dfde8e-c4a3-430f-ba33-5ad2c0aa94c9.png)

Thanks for the help.

**Comment by sagatowski** [comment] 2021-12-15 15:02
Duplicate of #19.

**Closed by sagatowski** 2021-12-15 15:02 UTC
